import { Poppins, Mulish } from 'next/font/google';
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-poppins',
});

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-mulish',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${mulish.variable}`}>
      <body className="font-mulish">
        {children}
      </body>
    </html>
  );
}
